export const branchAssignedEmployees = [
  {
    id: 321432345455355423,
    firstName: "Juan",
    lastName: "Dela Cruz",
    phoneNumber: "09171234567",
    position: "Store Manager",
  },
  {
    id: 2,
    firstName: "Maria",
    lastName: "Santos",
    phoneNumber: "09181234567",
    position: "Cashier",
  },
  {
    id: 3,
    firstName: "Jose",
    lastName: "Reyes",
    phoneNumber: "09191234567",
    position: "Inventory Clerk",
  },
  {
    id: 4,
    firstName: "Ana",
    lastName: "Garcia",
    phoneNumber: "09201234567",
    position: "Sales Associate",
  },
  {
    id: 5,
    firstName: "Mark",
    lastName: "Torres",
    phoneNumber: "09211234567",
    position: "Warehouse Staff",
  },
  {
    id: 6,
    firstName: "Claire",
    lastName: "Mendoza",
    phoneNumber: "09221234567",
    position: "Accountant",
  },
  {
    id: 7,
    firstName: "Paolo",
    lastName: "Fernandez",
    phoneNumber: "09231234567",
    position: "Supervisor",
  },
  {
    id: 8,
    firstName: "Jasmine",
    lastName: "Lopez",
    phoneNumber: "09241234567",
    position: "Customer Service Representative",
  },
  {
    id: 9,
    firstName: "Kevin",
    lastName: "Castillo",
    phoneNumber: "09251234567",
    position: "Delivery Driver",
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Villanueva",
    phoneNumber: "09261234567",
    position: "HR Assistant",
  },
];
