import { ProductType } from "@/types/ProductType";

export const products: ProductType[] = [
  {
    id: "1",
    name: "Chocolate Cake",
    size: "6 inch",
    price: 850,
    imageUrl: "/images/products/black forest.jpg",
    quantity: 10,
  },
  {
    id: "2",
    name: "Vanilla Cake",
    size: "8 inch",
    price: 1200,
    imageUrl: "/images/products/brigadeiro.jpg",
    quantity: 0,
  },
  {
    id: "3",
    name: "Red Velvet Cake",
    size: "10 inch",
    price: 1500,
    imageUrl:
      "/images/products/custom fathers day cake w fresh fruit toppings.jpg",
    quantity: 3,
  },
  {
    id: "4",
    name: "Strawberry Cake",
    size: "6 inch",
    price: 900,
    imageUrl: "/images/products/mangoGrahamFloat.jpg",
    quantity: 25,
  },
  {
    id: "5",
    name: "Black Forest Cake",
    size: "8 inch",
    price: 1300,
    imageUrl: "/images/products/original red velvet cake.jpg",
    quantity: 30,
  },
  {
    id: "6",
    name: "Mango Cake",
    size: "10 inch",
    price: 1600,
    imageUrl: "/images/products/red velvet cake.jpg",
    quantity: 35,
  },
  {
    id: "7",
    name: "Ube Cake",
    size: "6 inch",
    price: 950,
    imageUrl: "/images/products/ube cake.jpg",
    quantity: 40,
  },
  {
    id: "8",
    name: "Carrot Cake",
    size: "8 inch",
    price: 1100,
    imageUrl: "/images/products/yema cake.jpg",
    quantity: 45,
  },
  {
    id: "9",
    name: "Mocha Cake",
    size: "10 inch",
    price: 1400,
    imageUrl: "/images/products/yema ube cake.jpg",
    quantity: 50,
  },
  {
    id: "10",
    name: "Cheesecake",
    size: "6 inch",
    price: 1250,
    imageUrl: "/images/products/brigadeiro.jpg",
    quantity: 55,
  },
  {
    id: "11",
    name: "Chocolate Cake",
    size: "6 inch",
    price: 850,
    imageUrl: "/images/products/black forest.jpg",
    quantity: 10,
  },
  {
    id: "12",
    name: "Vanilla Cake",
    size: "8 inch",
    price: 1200,
    imageUrl: "/images/products/brigadeiro.jpg",
    quantity: 0,
  },
  {
    id: "13",
    name: "Red Velvet Cake",
    size: "10 inch",
    price: 1500,
    imageUrl:
      "/images/products/custom fathers day cake w fresh fruit toppings.jpg",
    quantity: 3,
  },
  {
    id: "14",
    name: "Strawberry Cake",
    size: "6 inch",
    price: 900,
    imageUrl: "/images/products/mangoGrahamFloat.jpg",
    quantity: 25,
  },
  {
    id: "15",
    name: "Black Forest Cake",
    size: "8 inch",
    price: 1300,
    imageUrl: "/images/products/original red velvet cake.jpg",
    quantity: 30,
  },
  {
    id: "16",
    name: "Mango Cake",
    size: "10 inch",
    price: 1600,
    imageUrl: "/images/products/red velvet cake.jpg",
    quantity: 35,
  },
  {
    id: "17",
    name: "Ube Cake",
    size: "6 inch",
    price: 950,
    imageUrl: "/images/products/ube cake.jpg",
    quantity: 40,
  },
  {
    id: "18",
    name: "Carrot Cake",
    size: "8 inch",
    price: 1100,
    imageUrl: "/images/products/yema cake.jpg",
    quantity: 45,
  },
  {
    id: "19",
    name: "Mocha Cake",
    size: "10 inch",
    price: 1400,
    imageUrl: "/images/products/yema ube cake.jpg",
    quantity: 50,
  },
  {
    id: "20",
    name: "Cheesecake",
    size: "6 inch",
    price: 1250,
    imageUrl: "/images/products/brigadeiro.jpg",
    quantity: 55,
  },
];
